#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS stellar;
    CREATE DATABASE IF NOT EXISTS stellar_core;
    CREATE DATABASE IF NOT EXISTS stellar_horizon;
    GRANT ALL PRIVILEGES ON DATABASE stellar TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE stellar_core TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE stellar_horizon TO $POSTGRES_USER;
EOSQL
